/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;




import java.awt.event.KeyEvent;
import java.util.Properties;
import javax.mail.Message;
import javax.mail.MessagingException;
import javax.mail.PasswordAuthentication;
import javax.mail.Session;
import javax.mail.Transport;
import javax.mail.internet.InternetAddress;
import javax.mail.internet.MimeMessage;
import mydao.NVDao;
import myentity.NhanVien;
import xhelper.Auth;
import xhelper.MyMess;
import xhelper.MyValidate;
/**
 *
 * @author NTV
 */
public class ForgotPassFrm extends javax.swing.JInternalFrame {

    private NVDao dao;
    private NhanVien nv;
    private String codeSMS;
    static int frmForgot = 0;

    /**
     * Creates new form ForgotPassFrm
     */
    public ForgotPassFrm() {
        initComponents();
        this.dao = new NVDao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTaiKhoan = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnOk = new javax.swing.JButton();
        txtOTP = new javax.swing.JTextField();
        lblTimeOut = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setResizable(true);
        setTitle("Quên mật khẩu?");
        setFont(new java.awt.Font("Agency FB", 0, 36)); // NOI18N
        getContentPane().setLayout(new java.awt.GridLayout(1, 0));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Nhập tài khoản:");

        txtTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTaiKhoan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTaiKhoanActionPerformed(evt);
            }
        });
        txtTaiKhoan.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTaiKhoanKeyPressed(evt);
            }
        });

        btnSearch.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSearch.setText("Tìm Kiếm");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });
        btnSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnSearchKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(131, 131, 131)
                                .addComponent(btnSearch)))
                        .addGap(0, 128, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtTaiKhoan)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTaiKhoan, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);

        btnOk.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnOk.setText("Xác Nhận");
        btnOk.setEnabled(false);
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });
        btnOk.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnOkKeyPressed(evt);
            }
        });

        txtOTP.setEditable(false);
        txtOTP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtOTP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOTPKeyPressed(evt);
            }
        });

        lblTimeOut.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblTimeOut.setForeground(new java.awt.Color(255, 0, 51));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel3.setText("Nhập Mã OTP:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtOTP))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(btnOk)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                        .addComponent(lblTimeOut)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jLabel3, lblTimeOut});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(lblTimeOut, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtOTP, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOk)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jLabel3, lblTimeOut});

        getContentPane().add(jPanel2);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String manv = txtTaiKhoan.getText();
        if (MyValidate.isEmpty(txtTaiKhoan)) {
            MyMess.msgFalse(this, "Nhập tài khoản cần tìm!");
            return;
        }
        nv = new NhanVien();
        try {
            nv = this.dao.selectByID(manv);
            if (nv == null) {
                MyMess.msgFalse(this, "Tài khoản này không tồn tại!");
                return;
            }
        } catch (Exception ex) {
            MyMess.msgFalse(this, "Lỗi truy vấn");
            return;
        }
        Auth.nguoiDungHienTai = nv;
        //gửi mail mã OTP
        if (sendEmail(nv)) {
            return;
        }
        thoiGianHieuLucOTP();
        btnOk.setEnabled(true);
        txtOTP.setEditable(true);
        btnSearch.setText("Gửi Lại");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        if (txtOTP.getText().trim().isEmpty()) {
            MyMess.msgFalse(this, "Bạn phải nhập mã OTP đã gửi đến email");
            return;
        } else if (!txtOTP.getText().equals(codeSMS)) {
            MyMess.msgFalse(this, "Bạn đã nhập sai mã OTP!");
            return;
        }        
        LogInFrm.frmLogIn = 2;
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void txtTaiKhoanKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTaiKhoanKeyPressed
        // TODO add your handling code here:
        EnterAcctions(evt);
    }//GEN-LAST:event_txtTaiKhoanKeyPressed

    private void txtOTPKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOTPKeyPressed
        // TODO add your handling code here:
        EnterAcctions1(evt);
    }//GEN-LAST:event_txtOTPKeyPressed

    private void btnSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnSearchKeyPressed
        // TODO add your handling code here:
        EnterAcctions(evt);
    }//GEN-LAST:event_btnSearchKeyPressed

    private void btnOkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnOkKeyPressed
        // TODO add your handling code here:
        EnterAcctions1(evt);
    }//GEN-LAST:event_btnOkKeyPressed

    private void txtTaiKhoanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTaiKhoanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTaiKhoanActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnSearch;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblTimeOut;
    private javax.swing.JTextField txtOTP;
    private javax.swing.JTextField txtTaiKhoan;
    // End of variables declaration//GEN-END:variables

    private boolean sendEmail(NhanVien nv) {
        codeSMS = String.format("%.0f", (Math.random() * (999999 - 111110 + 1) + 111110));
        final String username = "sendmail.fpttext@gmail.com";
        final String password = "sendmail.fpttext10";
        Properties prop = new Properties();
        prop.put("mail.smtp.auth", "true");
        prop.put("mail.smtp.starttls.enable", "true");
        prop.put("mail.smtp.host", "smtp.gmail.com");
        prop.put("mail.smtp.port", 587);

        Session session;
        session = Session.getInstance(prop, new javax.mail.Authenticator() {
            @Override
            protected PasswordAuthentication getPasswordAuthentication() {
                return new PasswordAuthentication(username, password);
            }
        });
        try {
            
            Message message = new MimeMessage(session);
            message.setFrom(new InternetAddress("sendmail.fpttext@gmail.com"));
            message.setRecipients(
                    Message.RecipientType.TO,
                    InternetAddress.parse(nv.getEmail())
            );
            message.setSubject("HE THONG DAO TAO EDUSYS");
            message.setText("Chào " + nv.getHoTen() + " \n"
                    + "Mã OTP của bạn là: " + codeSMS);
            String mail = nv.getEmail().substring(0, 3)+ "****" + nv.getEmail().substring(nv.getEmail().lastIndexOf("@"), nv.getEmail().length());
            Transport.send(message);
            MyMess.msgTrue(this, "Chúng tôi đã gửi mã OTP đến địa chỉ Email: "+ mail + ", \nBạn vui lòng kiểm tra hộp thư!");

        } catch (MessagingException e) {
            e.printStackTrace();
            MyMess.msgFalse(this, "Gửi mail thất bại");
            return true;

        }
        return false;
    }

    private void thoiGianHieuLucOTP() {
        //        if (sendEmail(nv)) return;
        
        new Thread() {
            @Override
            public void run() { 
                int i = 180;
                while (true) {
                    if (i == 1) {                        
                        btnOk.setEnabled(false);
                        lblTimeOut.setText("OTP đã hết hạn!");
                        txtOTP.setEditable(false);
                        this.stop();
                    }
                    lblTimeOut.setText(i + "s");
                    i--;
                    try {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex) {
                        ex.printStackTrace();
                    }
                }
            }
            
        }.start();
        
    }
    
    private void EnterAcctions(KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnSearch.doClick();
        }
    }
    
    private void EnterAcctions1(KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnOk.doClick();
        }
    }
}
