/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseListener;
import java.io.File;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JButton;
import javax.swing.JInternalFrame;
import javax.swing.Timer;
import javax.swing.event.InternalFrameEvent;
import javax.swing.event.InternalFrameListener;
import xhelper.Auth;
import xhelper.ImageHelper;
import xhelper.MyMess;

/**
 *
 * @author NTV
 */
public class MainFrm extends javax.swing.JFrame {

    private HelloScreenFrm hello;
    private HomeFrm homeFrm;
    private LogInFrm logInFrm;
    private ChangePassFrm changeFrm;
    private QLCDFrm qLCDFrm;
    private QLHVFrm qLHVFrm;
    private QLKHFrm qLKHFrm;
    private QLNHFrm qLNHFrm;
    private QLNVFrm qLNVFrm;
    private ForgotPassFrm frmForgot;
    private StatisticalFrm frmStatis;
    private InfoFrm frmInfo;

    /**
     * Creates new form MainFrm
     */
    public MainFrm() {
        initComponents();
        //setLocationRelativeTo(null);
        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setSize(screenSize.width, screenSize.height);
        setResizable(false);

        init();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dpMain = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        btnHome = new javax.swing.JButton();
        btnQLNhanVien = new javax.swing.JButton();
        btnQLCD = new javax.swing.JButton();
        btnQLHV = new javax.swing.JButton();
        btnQLKH = new javax.swing.JButton();
        btnQLNH = new javax.swing.JButton();
        btnBCTK = new javax.swing.JButton();
        lblRule = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblClock = new javax.swing.JLabel();
        lblDate = new javax.swing.JLabel();
        MnuBar = new javax.swing.JMenuBar();
        MnuHeThong = new javax.swing.JMenu();
        mnuLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuChangePass = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuExit = new javax.swing.JMenuItem();
        mnuQuanLy = new javax.swing.JMenu();
        mnuCD = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        mnuKH = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnuNH = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnuHV = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnuNV = new javax.swing.JMenuItem();
        mnuThongKe = new javax.swing.JMenu();
        mnuBD = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnuLuNH = new javax.swing.JMenuItem();
        jSeparator8 = new javax.swing.JPopupMenu.Separator();
        mnuDCD = new javax.swing.JMenuItem();
        jSeparator9 = new javax.swing.JPopupMenu.Separator();
        mnuDT = new javax.swing.JMenuItem();
        MnuTroGiup = new javax.swing.JMenu();
        mnuHuongDan = new javax.swing.JMenuItem();
        jSeparator10 = new javax.swing.JPopupMenu.Separator();
        mnuGioiThieu = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("The Dark Knight");
        setAlwaysOnTop(true);
        setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N

        javax.swing.GroupLayout dpMainLayout = new javax.swing.GroupLayout(dpMain);
        dpMain.setLayout(dpMainLayout);
        dpMainLayout.setHorizontalGroup(
            dpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        dpMainLayout.setVerticalGroup(
            dpMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 626, Short.MAX_VALUE)
        );

        jPanel1.setLayout(new java.awt.GridLayout(1, 0, 20, 0));

        btnHome.setBackground(new java.awt.Color(255, 255, 255));
        btnHome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHome.setForeground(new java.awt.Color(255, 255, 255));
        btnHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/home.png"))); // NOI18N
        btnHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });
        jPanel1.add(btnHome);

        btnQLNhanVien.setBackground(new java.awt.Color(255, 255, 255));
        btnQLNhanVien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnQLNhanVien.setForeground(new java.awt.Color(255, 255, 255));
        btnQLNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/R.png"))); // NOI18N
        btnQLNhanVien.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLNhanVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNhanVienActionPerformed(evt);
            }
        });
        jPanel1.add(btnQLNhanVien);

        btnQLCD.setBackground(new java.awt.Color(255, 255, 255));
        btnQLCD.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnQLCD.setForeground(new java.awt.Color(255, 255, 255));
        btnQLCD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/listicon.jpg"))); // NOI18N
        btnQLCD.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLCDActionPerformed(evt);
            }
        });
        jPanel1.add(btnQLCD);

        btnQLHV.setBackground(new java.awt.Color(255, 255, 255));
        btnQLHV.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnQLHV.setForeground(new java.awt.Color(255, 255, 255));
        btnQLHV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/studenicon.jpg"))); // NOI18N
        btnQLHV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLHV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLHVActionPerformed(evt);
            }
        });
        jPanel1.add(btnQLHV);

        btnQLKH.setBackground(new java.awt.Color(255, 255, 255));
        btnQLKH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnQLKH.setForeground(new java.awt.Color(255, 255, 255));
        btnQLKH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/courseicon.jpg"))); // NOI18N
        btnQLKH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLKHActionPerformed(evt);
            }
        });
        jPanel1.add(btnQLKH);

        btnQLNH.setBackground(new java.awt.Color(255, 255, 255));
        btnQLNH.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnQLNH.setForeground(new java.awt.Color(255, 255, 255));
        btnQLNH.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/multipleuser.png"))); // NOI18N
        btnQLNH.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnQLNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQLNHActionPerformed(evt);
            }
        });
        jPanel1.add(btnQLNH);

        btnBCTK.setBackground(new java.awt.Color(255, 255, 255));
        btnBCTK.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnBCTK.setForeground(new java.awt.Color(255, 255, 255));
        btnBCTK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/statisticalicon.png"))); // NOI18N
        btnBCTK.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnBCTK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBCTKActionPerformed(evt);
            }
        });
        jPanel1.add(btnBCTK);

        lblRule.setBackground(new java.awt.Color(255, 255, 255));
        lblRule.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblRule.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblRule.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/info48.jpg"))); // NOI18N
        lblRule.setText("Hệ quản lý đào tạo");

        jPanel2.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(240, 240, 240), 5)));
        jPanel2.setLayout(new java.awt.GridLayout(2, 0, 0, -15));

        lblClock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblClock.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblClock.setText("00:00 AM");
        lblClock.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lblClock);
        lblClock.getAccessibleContext().setAccessibleParent(lblClock);

        lblDate.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDate.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDate.setText("18/02/2022");
        jPanel2.add(lblDate);

        MnuBar.setMargin(new java.awt.Insets(0, 10, 0, 10));
        MnuBar.setPreferredSize(new java.awt.Dimension(310, 50));

        MnuHeThong.setText("Hệ thống");
        MnuHeThong.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MnuHeThong.setMargin(new java.awt.Insets(0, 10, 0, 10));

        mnuLogout.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mnuLogout.setText("Đăng Nhập");
        mnuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLogoutActionPerformed(evt);
            }
        });
        MnuHeThong.add(mnuLogout);
        MnuHeThong.add(jSeparator1);

        mnuChangePass.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mnuChangePass.setText("Đổi mật khẩu");
        mnuChangePass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuChangePassActionPerformed(evt);
            }
        });
        MnuHeThong.add(mnuChangePass);
        MnuHeThong.add(jSeparator2);

        mnuExit.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mnuExit.setText("Thoát");
        mnuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuExitActionPerformed(evt);
            }
        });
        MnuHeThong.add(mnuExit);

        MnuBar.add(MnuHeThong);

        mnuQuanLy.setBorder(null);
        mnuQuanLy.setText("Quản lý");
        mnuQuanLy.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mnuQuanLy.setMargin(new java.awt.Insets(0, 10, 0, 10));

        mnuCD.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mnuCD.setText("Chuyên đề");
        mnuCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCDActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mnuCD);
        mnuQuanLy.add(jSeparator3);

        mnuKH.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mnuKH.setText("Khoá học");
        mnuKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuKHActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mnuKH);
        mnuQuanLy.add(jSeparator4);

        mnuNH.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mnuNH.setText("Người học");
        mnuNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNHActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mnuNH);
        mnuQuanLy.add(jSeparator5);

        mnuHV.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mnuHV.setText("Học viên");
        mnuHV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHVActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mnuHV);
        mnuQuanLy.add(jSeparator6);

        mnuNV.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mnuNV.setText("Nhân viên");
        mnuNV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuNVActionPerformed(evt);
            }
        });
        mnuQuanLy.add(mnuNV);

        MnuBar.add(mnuQuanLy);

        mnuThongKe.setText("Thống kê");
        mnuThongKe.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mnuThongKe.setMargin(new java.awt.Insets(0, 10, 0, 10));

        mnuBD.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mnuBD.setText("Bảng điểm");
        mnuBD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuBDActionPerformed(evt);
            }
        });
        mnuThongKe.add(mnuBD);
        mnuThongKe.add(jSeparator7);

        mnuLuNH.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mnuLuNH.setText("Lượng người học");
        mnuLuNH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuLuNHActionPerformed(evt);
            }
        });
        mnuThongKe.add(mnuLuNH);
        mnuThongKe.add(jSeparator8);

        mnuDCD.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mnuDCD.setText("Điểm chuyên đề");
        mnuDCD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDCDActionPerformed(evt);
            }
        });
        mnuThongKe.add(mnuDCD);
        mnuThongKe.add(jSeparator9);

        mnuDT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mnuDT.setText("Doanh thu");
        mnuDT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDTActionPerformed(evt);
            }
        });
        mnuThongKe.add(mnuDT);

        MnuBar.add(mnuThongKe);

        MnuTroGiup.setBorder(null);
        MnuTroGiup.setText("Trợ giúp");
        MnuTroGiup.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MnuTroGiup.setMargin(new java.awt.Insets(0, 10, 0, 10));

        mnuHuongDan.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mnuHuongDan.setText("Hướng dẫn");
        mnuHuongDan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuHuongDanActionPerformed(evt);
            }
        });
        MnuTroGiup.add(mnuHuongDan);
        MnuTroGiup.add(jSeparator10);

        mnuGioiThieu.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        mnuGioiThieu.setText("Giới thiệu");
        mnuGioiThieu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGioiThieuActionPerformed(evt);
            }
        });
        MnuTroGiup.add(mnuGioiThieu);

        MnuBar.add(MnuTroGiup);

        setJMenuBar(MnuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(dpMain)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRule, javax.swing.GroupLayout.PREFERRED_SIZE, 372, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 956, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(dpMain)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRule, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnuHuongDanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHuongDanActionPerformed
        String path = ".\\pages\\index.html";
        this.setAlwaysOnTop(false);
        try {
            Desktop.getDesktop().open(new File(path));
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_mnuHuongDanActionPerformed

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
        // TODO add your handling code here:
        this.setAlwaysOnTop(true);
        closeAllFrm();
        if (homeFrm == null || homeFrm.isClosed()) {
            homeFrm = new HomeFrm();
            homeFrm.addInternalFrameListener(new InternalFrameListener() {
                @Override
                public void internalFrameOpened(InternalFrameEvent e) {
                }

                @Override
                public void internalFrameClosing(InternalFrameEvent e) {

                }

                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                    statusBtn();
                    if (HomeFrm.home == 1) {
                        mnuLogoutActionPerformed(null);
                    } else if (HomeFrm.home == 2) {
                        mnuChangePassActionPerformed(null);
                    }else if (HomeFrm.home == 4 ) {
                        mnuGioiThieuActionPerformed(null);
                    }else if (HomeFrm.home == 5) {
                        mnuHuongDanActionPerformed(null);
                    }
                }

                @Override
                public void internalFrameIconified(InternalFrameEvent e) {
                }

                @Override
                public void internalFrameDeiconified(InternalFrameEvent e) {
                }

                @Override
                public void internalFrameActivated(InternalFrameEvent e) {
                }

                @Override
                public void internalFrameDeactivated(InternalFrameEvent e) {
                }
            });
            dpMain.add(homeFrm);
            homeFrm.setSize(dpMain.getWidth(), dpMain.getHeight());
            homeFrm.setVisible(true);
        } else {
            homeFrm.setVisible(true);
        }
    }//GEN-LAST:event_btnHomeActionPerformed

    private void mnuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLogoutActionPerformed
        closeAllFrm();
        this.setAlwaysOnTop(true);
        if (mnuLogout.getText().equalsIgnoreCase("Đăng Nhập")) {
            Auth.nguoiDungHienTai = null;
        }
        if (logInFrm == null || logInFrm.isClosed()) {
            logInFrm = new LogInFrm();
            logInFrm.addInternalFrameListener(new InternalFrameListener() {
                @Override
                public void internalFrameOpened(InternalFrameEvent e) {
                    statusBtn();
                    lblRule.setText(Auth.nguoiDungHienTai == null ? "Hãy Đăng Nhập Để Sử Dụng"
                            : (Auth.isManager()? "Trưởng Phòng: " + Auth.nguoiDungHienTai.getHoTen() 
                                    : "Nhân Viên: " + Auth.nguoiDungHienTai.getHoTen()));
                }

                @Override
                public void internalFrameClosing(InternalFrameEvent e) {
                }

                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                    statusBtn();
                    if (ForgotPassFrm.frmForgot == 2) {
                        if (frmForgot == null || frmForgot.isClosed()) {
                            frmForgot = new ForgotPassFrm();
                            frmForgot.addInternalFrameListener(new InternalFrameListener() {
                                @Override
                                public void internalFrameOpened(InternalFrameEvent e) {
                                }

                                @Override
                                public void internalFrameClosing(InternalFrameEvent e) {

                                }

                                @Override
                                public void internalFrameClosed(InternalFrameEvent e) {
                                    if (LogInFrm.frmLogIn == 2) {
                                        mnuChangePassActionPerformed(null);
                                    }
                                }

                                @Override
                                public void internalFrameIconified(InternalFrameEvent e) {
                                }

                                @Override
                                public void internalFrameDeiconified(InternalFrameEvent e) {
                                }

                                @Override
                                public void internalFrameActivated(InternalFrameEvent e) {
                                }

                                @Override
                                public void internalFrameDeactivated(InternalFrameEvent e) {
                                }
                            });
                            frmForgot.setLocation(dpMain.getWidth() / 2 - frmForgot.getWidth() / 2,
                                    dpMain.getHeight() / 2 - frmForgot.getHeight() / 2);
                            dpMain.add(frmForgot);
                            frmForgot.setVisible(true);
                        }
                    }

                    if (LogInFrm.frmLogIn == 0) {
                        btnHomeActionPerformed(null);
                    }
                    
                    lblRule.setText(Auth.nguoiDungHienTai == null ? "Hãy Đăng Nhập Để Sử Dụng Các Chức Năng"
                            : (Auth.isManager()? "Trưởng Phòng: " + Auth.nguoiDungHienTai.getHoTen() 
                                    : "Nhân Viên: " + Auth.nguoiDungHienTai.getHoTen()));
        
                }

                @Override
                public void internalFrameIconified(InternalFrameEvent e) {
                }

                @Override
                public void internalFrameDeiconified(InternalFrameEvent e) {
                }

                @Override
                public void internalFrameActivated(InternalFrameEvent e) {
                    mnuLogout.setText("Đăng Nhập");
                }

                @Override
                public void internalFrameDeactivated(InternalFrameEvent e) {
                }
            });
            logInFrm.setLocation(dpMain.getWidth() / 2 - logInFrm.getWidth() / 2,
                    dpMain.getHeight() / 2 - logInFrm.getHeight() / 2);

            dpMain.add(logInFrm);
            logInFrm.setVisible(true);
        } else {
            logInFrm.setVisible(true);
        }
        if (logInFrm.isClosed()) {
            btnHomeActionPerformed(null);
        }
    }//GEN-LAST:event_mnuLogoutActionPerformed

    private void mnuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuExitActionPerformed
        if (!MyMess.question(this, "Bạn muốn thoát chương trình?")) {
            return;
        }
    }//GEN-LAST:event_mnuExitActionPerformed

    private void mnuChangePassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuChangePassActionPerformed
        closeAllFrm();
        this.setAlwaysOnTop(true);
        if (changeFrm == null || changeFrm.isClosed()) {
            if (LogInFrm.frmLogIn == 2) {
                changeFrm = new ChangePassFrm(false);
            } else {
                changeFrm = new ChangePassFrm(true);
            }
            changeFrm.addInternalFrameListener(new InternalFrameListener() {
                @Override
                public void internalFrameOpened(InternalFrameEvent e) {
                }

                @Override
                public void internalFrameClosing(InternalFrameEvent e) {

                }

                @Override
                public void internalFrameClosed(InternalFrameEvent e) {
                    if (ChangePassFrm.changePass == 1) {
                        mnuLogoutActionPerformed(null);
                    }
                }

                @Override
                public void internalFrameIconified(InternalFrameEvent e) {
                }

                @Override
                public void internalFrameDeiconified(InternalFrameEvent e) {
                }

                @Override
                public void internalFrameActivated(InternalFrameEvent e) {
                }

                @Override
                public void internalFrameDeactivated(InternalFrameEvent e) {
                }
            });
            dpMain.add(changeFrm);
            changeFrm.setLocation(dpMain.getWidth() / 2 - changeFrm.getWidth() / 2, dpMain.getHeight() / 2 - changeFrm.getHeight() / 2);
            changeFrm.setVisible(true);
        } else {
            changeFrm.setVisible(true);
        }

    }//GEN-LAST:event_mnuChangePassActionPerformed

    private void mnuCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCDActionPerformed
        closeAllFrm();
        this.setAlwaysOnTop(true);
        if (qLCDFrm == null || qLCDFrm.isClosed()) {
            qLCDFrm = new QLCDFrm();
            dpMain.add(qLCDFrm);
            qLCDFrm.setSize(dpMain.getWidth(), dpMain.getHeight());
            qLCDFrm.setVisible(true);
        } else {
            qLCDFrm.setVisible(true);
        }
    }//GEN-LAST:event_mnuCDActionPerformed

    private void mnuKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuKHActionPerformed
        closeAllFrm();
        this.setAlwaysOnTop(true);
        if (qLKHFrm == null || qLKHFrm.isClosed()) {
            qLKHFrm = new QLKHFrm();
            dpMain.add(qLKHFrm);
            qLKHFrm.setSize(dpMain.getWidth(), dpMain.getHeight());
            qLKHFrm.setVisible(true);
        } else {
            qLKHFrm.setVisible(true);
        }
    }//GEN-LAST:event_mnuKHActionPerformed

    private void mnuNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNHActionPerformed
        closeAllFrm();
        this.setAlwaysOnTop(true);
        if (qLNHFrm == null || qLNHFrm.isClosed()) {
            qLNHFrm = new QLNHFrm();
            dpMain.add(qLNHFrm);
            qLNHFrm.setSize(dpMain.getWidth(), dpMain.getHeight());
            qLNHFrm.setVisible(true);
        } else {
            qLNHFrm.setVisible(true);
        }
    }//GEN-LAST:event_mnuNHActionPerformed

    private void mnuHVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuHVActionPerformed
        closeAllFrm();
        this.setAlwaysOnTop(true);
        if (qLHVFrm == null || qLHVFrm.isClosed()) {
            qLHVFrm = new QLHVFrm();
            dpMain.add(qLHVFrm);
            qLHVFrm.setSize(dpMain.getWidth(), dpMain.getHeight());
            qLHVFrm.setVisible(true);
        } else {
            qLHVFrm.setVisible(true);
        }
    }//GEN-LAST:event_mnuHVActionPerformed

    private void mnuNVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuNVActionPerformed
        closeAllFrm();
        this.setAlwaysOnTop(true);
        if (qLNVFrm == null || qLNVFrm.isClosed()) {
            qLNVFrm = new QLNVFrm();
            dpMain.add(qLNVFrm);
            qLNVFrm.setSize(dpMain.getWidth(), dpMain.getHeight());
            qLNVFrm.setVisible(true);
        } else {
            qLNVFrm.setVisible(true);
        }
    }//GEN-LAST:event_mnuNVActionPerformed

    private void btnQLNhanVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNhanVienActionPerformed
        // TODO add your handling code here:
        mnuNVActionPerformed(null);
    }//GEN-LAST:event_btnQLNhanVienActionPerformed

    private void btnQLCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLCDActionPerformed
        // TODO add your handling code here:
        mnuCDActionPerformed(null);
    }//GEN-LAST:event_btnQLCDActionPerformed

    private void btnQLHVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLHVActionPerformed
        // TODO add your handling code here:
        mnuHVActionPerformed(null);
    }//GEN-LAST:event_btnQLHVActionPerformed

    private void btnQLKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLKHActionPerformed
        // TODO add your handling code here:
        mnuKHActionPerformed(null);
    }//GEN-LAST:event_btnQLKHActionPerformed

    private void btnQLNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQLNHActionPerformed
        // TODO add your handling code here:
        mnuNHActionPerformed(null);
    }//GEN-LAST:event_btnQLNHActionPerformed

    private void btnBCTKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBCTKActionPerformed
        // TODO add your handling code here:
        closeAllFrm();
        this.setAlwaysOnTop(true);
        if (frmStatis == null || frmStatis.isClosed()) {
            frmStatis = new StatisticalFrm();
            dpMain.add(frmStatis);
            frmStatis.setSize(dpMain.getWidth(), dpMain.getHeight());
            frmStatis.setVisible(true);
        } else {
            frmStatis.setVisible(true);
        }
    }//GEN-LAST:event_btnBCTKActionPerformed

    private void mnuBDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuBDActionPerformed
        // TODO add your handling code here:
        closeAllFrm();
        this.setAlwaysOnTop(true);
        if (frmStatis == null || frmStatis.isClosed()) {
            frmStatis = new StatisticalFrm();
            dpMain.add(frmStatis);
            frmStatis.setSize(dpMain.getWidth(), dpMain.getHeight());
            frmStatis.selectTab(0);
            frmStatis.setVisible(true);
        } else {
            frmStatis.selectTab(0);
            frmStatis.setVisible(true);
        }
    }//GEN-LAST:event_mnuBDActionPerformed

    private void mnuLuNHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuLuNHActionPerformed
        // TODO add your handling code here:
        closeAllFrm();
        this.setAlwaysOnTop(true);
        if (frmStatis == null || frmStatis.isClosed()) {
            frmStatis = new StatisticalFrm();
            dpMain.add(frmStatis);
            frmStatis.setSize(dpMain.getWidth(), dpMain.getHeight());
            frmStatis.selectTab(1);
            frmStatis.setVisible(true);
        } else {
            frmStatis.setVisible(true);
        }
    }//GEN-LAST:event_mnuLuNHActionPerformed

    private void mnuDCDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDCDActionPerformed
        // TODO add your handling code here:
        closeAllFrm();
        this.setAlwaysOnTop(true);
        if (frmStatis == null || frmStatis.isClosed()) {
            frmStatis = new StatisticalFrm();
            dpMain.add(frmStatis);
            frmStatis.setSize(dpMain.getWidth(), dpMain.getHeight());
            frmStatis.selectTab(2);
            frmStatis.setVisible(true);
        } else {
            frmStatis.setVisible(true);
        }
    }//GEN-LAST:event_mnuDCDActionPerformed

    private void mnuDTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDTActionPerformed
        // TODO add your handling code here:
        closeAllFrm();
        this.setAlwaysOnTop(true);
        if (frmStatis == null || frmStatis.isClosed()) {
            frmStatis = new StatisticalFrm();
            dpMain.add(frmStatis);
            frmStatis.setSize(dpMain.getWidth(), dpMain.getHeight());
            frmStatis.selectTab(3);
            frmStatis.setVisible(true);
        } else {
            frmStatis.setVisible(true);
        }
    }//GEN-LAST:event_mnuDTActionPerformed

    private void mnuGioiThieuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGioiThieuActionPerformed
        // TODO add your handling code here:
        closeAllFrm();
        this.setAlwaysOnTop(true);
        if (frmInfo == null || frmInfo.isClosed()) {
            frmInfo = new InfoFrm();
            dpMain.add(frmInfo);
            frmInfo.setSize(dpMain.getWidth(), dpMain.getHeight());
            frmInfo.setVisible(true);
        } else {
            frmInfo.setVisible(true);
        }
    }//GEN-LAST:event_mnuGioiThieuActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar MnuBar;
    private javax.swing.JMenu MnuHeThong;
    private javax.swing.JMenu MnuTroGiup;
    private javax.swing.JButton btnBCTK;
    private javax.swing.JButton btnHome;
    private javax.swing.JButton btnQLCD;
    private javax.swing.JButton btnQLHV;
    private javax.swing.JButton btnQLKH;
    private javax.swing.JButton btnQLNH;
    private javax.swing.JButton btnQLNhanVien;
    private javax.swing.JDesktopPane dpMain;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator10;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JPopupMenu.Separator jSeparator8;
    private javax.swing.JPopupMenu.Separator jSeparator9;
    private javax.swing.JLabel lblClock;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblRule;
    private javax.swing.JMenuItem mnuBD;
    private javax.swing.JMenuItem mnuCD;
    private javax.swing.JMenuItem mnuChangePass;
    private javax.swing.JMenuItem mnuDCD;
    private javax.swing.JMenuItem mnuDT;
    private javax.swing.JMenuItem mnuExit;
    private javax.swing.JMenuItem mnuGioiThieu;
    private javax.swing.JMenuItem mnuHV;
    private javax.swing.JMenuItem mnuHuongDan;
    private javax.swing.JMenuItem mnuKH;
    private javax.swing.JMenuItem mnuLogout;
    private javax.swing.JMenuItem mnuLuNH;
    private javax.swing.JMenuItem mnuNH;
    private javax.swing.JMenuItem mnuNV;
    private javax.swing.JMenu mnuQuanLy;
    private javax.swing.JMenu mnuThongKe;
    // End of variables declaration//GEN-END:variables

    private void init() {
        hello = new HelloScreenFrm(this, true);
        hello.setVisible(true);
        mnuLogoutActionPerformed(null);
        this.setIconImage(ImageHelper.getAppIcon());
        
        startDongHo();
        mouseHover();
    }

    private void startDongHo() {
        //Hiển thị đồng hồ        
        new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Date now = new Date();
                SimpleDateFormat fm1 = new SimpleDateFormat("dd/MM/yyyy");
                SimpleDateFormat fm = new SimpleDateFormat("hh:mm:ss a");
                String txt1 = fm1.format(now);
                lblDate.setText(txt1);
                String txt = fm.format(now);
                lblClock.setText(txt);
            }
        }).start();
    }

    private void statusBtn() {
        
        if (Auth.nguoiDungHienTai == null) {
            mnuLogout.setText("Đăng Nhập");
            mnuQuanLy.setEnabled(false);
            mnuThongKe.setEnabled(false);
            btnBCTK.setEnabled(false);
            btnQLCD.setEnabled(false);
            btnQLHV.setEnabled(false);
            btnQLKH.setEnabled(false);
            btnQLNH.setEnabled(false);
            btnQLNhanVien.setEnabled(false);
            mnuChangePass.setEnabled(false);

        } else {
            mnuLogout.setText("Đăng Xuất");
            mnuQuanLy.setEnabled(true);
            mnuThongKe.setEnabled(true);
            btnBCTK.setEnabled(true);
            btnQLCD.setEnabled(true);
            btnQLHV.setEnabled(true);
            btnQLKH.setEnabled(true);
            btnQLNH.setEnabled(true);
            btnQLNhanVien.setEnabled(true);
            mnuChangePass.setEnabled(true);
        }
        if(!Auth.isManager()) {
            btnQLNhanVien.setEnabled(false);
            mnuNV.setEnabled(false);
            mnuDT.setEnabled(false);
        }else {
            mnuDT.setEnabled(true);
        }
    }

    private void closeAllFrm() {
        // TODO add your handling code here:
        for (JInternalFrame frame : dpMain.getAllFrames()) {
            frame.dispose();
        }
    }

    private void mouseHover() {
        //Hiệu ứng di chuột vào các button menu
        JButton[] btns = {btnHome, btnQLNhanVien, btnQLCD, btnQLNH, btnQLKH, btnQLHV, btnBCTK};
        for (JButton btn : btns) {

            btn.setBackground(new Color(255, 255, 255));
//            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent e) {
                }

                @Override
                public void mousePressed(java.awt.event.MouseEvent e) {
                }

                @Override
                public void mouseReleased(java.awt.event.MouseEvent e) {
                }

                @Override
                public void mouseEntered(java.awt.event.MouseEvent e) {
                    btn.setBackground(new Color(54, 81, 207));
                    btn.setVerticalTextPosition(3);
                    if (btn == btnHome) {
                        btn.setText("Trang Chủ");
                    } else if (btn == btnQLCD) {
                        btn.setText("Chuyên Đề");
                    } else if (btn == btnQLHV) {
                        btn.setText("Học Viên");
                    } else if (btn == btnQLKH) {
                        btn.setText("Khoá Học");
                    } else if (btn == btnQLNH) {
                        btn.setText("Người Học");
                    } else if (btn == btnQLNhanVien) {
                        btn.setText("Nhân Viên");
                    } else if (btn == btnBCTK) {
                        btn.setText("Thống Kê");
                    }
                }

                @Override
                public void mouseExited(java.awt.event.MouseEvent e) {
                    btn.setBackground(new Color(255, 255, 255));
//                    btn.setVerticalAlignment(2);
                    if (btn == btnHome) {
                        btn.setText("");
                    } else if (btn == btnQLCD) {
                        btn.setText("");
                    } else if (btn == btnQLHV) {
                        btn.setText("");
                    } else if (btn == btnQLKH) {
                        btn.setText("");
                    } else if (btn == btnQLNH) {
                        btn.setText("");
                    } else if (btn == btnQLNhanVien) {
                        btn.setText("");
                    } else if (btn == btnBCTK) {
                        btn.setText("");
                    }
                }
            });
        }
    }
}
