/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Color;
import java.awt.event.KeyEvent;
import mydao.NVDao;
import myinterfaces.BaseDaoInterface;
import xhelper.Auth;
import xhelper.MyMess;
import xhelper.MyValidate;

/**
 *
 * @author NTV
 */
public class ChangePassFrm extends javax.swing.JInternalFrame {

    private BaseDaoInterface dao;
    static int changePass = 0;
    boolean kt;

    /**
     * Creates new form ChangePass
     */
    public ChangePassFrm(boolean kt) {
        initComponents();
        this.dao = new NVDao();
        this.kt = kt;
        if (!kt) {
            txtPassHT.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtPassHT = new javax.swing.JPasswordField();
        txtPassNew2 = new javax.swing.JPasswordField();
        txtPassNew = new javax.swing.JPasswordField();
        btnDongy = new javax.swing.JButton();
        btnHuy = new javax.swing.JButton();

        setResizable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Đổi Mật Khẩu");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Mật khẩu hiện tại:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Mật khẩu mới:");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setText("Xác nhận mật khẩu:");

        txtPassHT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPassHT.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassHTKeyPressed(evt);
            }
        });

        txtPassNew2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPassNew2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassNew2KeyPressed(evt);
            }
        });

        txtPassNew.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtPassNew.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassNewKeyPressed(evt);
            }
        });

        btnDongy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnDongy.setText("Đồng ý");
        btnDongy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDongyActionPerformed(evt);
            }
        });
        btnDongy.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnDongyKeyPressed(evt);
            }
        });

        btnHuy.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnHuy.setText("Huỷ bỏ");
        btnHuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtPassNew, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(txtPassHT, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addContainerGap(82, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDongy)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHuy))
                            .addComponent(txtPassNew2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPassHT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtPassNew2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDongy)
                    .addComponent(btnHuy))
                .addGap(0, 53, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDongyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDongyActionPerformed
        // TODO add your handling code here:
        StringBuilder sb = new StringBuilder();
        String pass1 = new String(txtPassHT.getPassword()),
                pass2 = new String(txtPassNew.getPassword()),
                pass3 = new String(txtPassNew2.getPassword());
        if (kt) {
            if (MyValidate.isEmpty(txtPassHT)) {
                sb.append("Nhập mật khẩu hiện tại\n");
                if (!pass1.equals(Auth.nguoiDungHienTai.getMatKhau())) {
                    sb.append("Bạn đã nhập sai mật khẩu hiện tại\n");
                    MyMess.msgFalse(this, sb.toString());
                    return;
                }
            }
        }
        if (MyValidate.isEmpty(txtPassNew)) {
            sb.append("Nhập mật khẩu mới\n");
        }

        if (MyValidate.isEmpty(txtPassNew2)) {
            sb.append("Nhập lại mật khẩu mới\n");
        }

        if (!pass3.equals(pass2)) {
            sb.append("Mật khẩu mới không trùng khớp\n");
            txtPassNew2.setBackground(Color.yellow);
            txtPassNew2.requestFocus();
        }
        String msg = sb.toString();
        if (msg.length() > 0) {
            MyMess.msgFalse(this, msg);
            return;
        }
        Auth.nguoiDungHienTai.setMatKhau(pass2);
        try {
            if (dao.update(Auth.nguoiDungHienTai)) {
                MyMess.msgTrue(this, "Đổi mật khẩu thành công!\nMời bạn đăng nhập lại");
                Auth.nguoiDungHienTai = null;
                changePass = 0;
                LogInFrm.frmLogIn = 1;
                HomeFrm.home = 0;
                ForgotPassFrm.frmForgot = 0;
                this.dispose();
            }
        } catch (Exception ex) {
            sb.append(ex.getMessage());
            MyMess.msgFalse(this, sb.toString());
            return;
        }

    }//GEN-LAST:event_btnDongyActionPerformed

    private void btnHuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnHuyActionPerformed

    private void txtPassHTKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassHTKeyPressed
        // TODO add your handling code here:
        EnterAcctions(evt);
    }//GEN-LAST:event_txtPassHTKeyPressed

    private void txtPassNewKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassNewKeyPressed
        // TODO add your handling code here:
        EnterAcctions(evt);
    }//GEN-LAST:event_txtPassNewKeyPressed

    private void txtPassNew2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassNew2KeyPressed
        // TODO add your handling code here:
        EnterAcctions(evt);
    }//GEN-LAST:event_txtPassNew2KeyPressed

    private void btnDongyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnDongyKeyPressed
        // TODO add your handling code here:
        EnterAcctions(evt);
    }//GEN-LAST:event_btnDongyKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDongy;
    private javax.swing.JButton btnHuy;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPasswordField txtPassHT;
    private javax.swing.JPasswordField txtPassNew;
    private javax.swing.JPasswordField txtPassNew2;
    // End of variables declaration//GEN-END:variables

    private void EnterAcctions(KeyEvent evt) {
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnDongy.doClick();
        }
    }

}
